%% This file is part of Chatterbox released
%% under the MIT License.

case erlang:function_exported(rebar3, main, 1) of
    true ->
        % rebar3
        CONFIG;
    false ->
        % rebar2
        Deps = [
            {hpack, ".*", {git, "https://github.com/davisp/hpack.git", {branch, "complete-rfc-implementation"}}}
        ],
        [{deps, Deps} | lists:keydelete(deps, 1, CONFIG)]
end.
